### ISSUE TITLE
Anything I can do to help with Database.GetBlock?

### ISSUE THREAD

**Issue by faddat** [go-steem/rpc#9]
If there is, please let me know.

**Comment by faddat** [comment]
faddat@gmail.com

So, I'd really love to talk with you.  Am I right that the bit that gave you trouble was the constantly changing operations array?

**Comment by tchap** [comment]
@faddat I am not sure what this issue is about really. Can you elaborate?

**Comment by tchap** [comment]
@faddat Is this connected to the pull requests you opened?

**Comment by faddat** [comment]
No, it's not.  Okay, so I think that you have the same difficulty, and if you don't well then I'm all-ears and then some.  Baiscally, because of the varying operation type, I have not been able to put together a struct that I can unmarshal GetBlockRaw onto.  I've looked through the source code here, and I think that I see attempts at making many types of structs, that might be usable in fully-go-ifying get_block commands.  

Or, maybe you already solved this, and I was totally unaware of how to use it.  Still fairly new when it comes to go.

**Comment by tchap** [comment]
@faddat But there is `GetBlock` that already returns the unmarshalled object, see https://godoc.org/github.com/go-steem/rpc/apis/database#API.GetBlock

**Comment by tchap** [comment]
@faddat The raw methods are for the cases when there is no method implemented yet, or there is an unmarshalling error and I need to check what the raw content is. In general always check whether the method returning an unmarshalled object exists. In general you should not need to use any `Raw` method, unless you want to implement a missing call or want to get raw data...

**Comment by faddat** [comment]
The problem, in sum, is that I am still trying to build some JSON that
actually takes all 5.5 million blocks.  This ins't really a bug in your
code.  STEEM did NOT make this easy....

Each time I think I've got the right struct for the JSON, something
explodes.. because there's what-- 120ish operation types?

Anyway man, I'm just not that great at working with JSON yet-- or the steem
api is really insane.  I don't honestly know which.  Thank you for your
help though.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by tchap** [comment]
Well, this should be possible. If it is not possible, it could be a bug in `go-steem/rpc`. But true, the API is pretty messed up to be honest. There were multiple changes to the format and some things are clearly making it harder, like using tuples containing multiple types instead of objects.

In any case, you can try to post the exact issue you are fighting with and I can try to help. Although I am leaving in the afternoon to be AFK for a week or something...

**Comment by faddat** [comment]
so the app where I'm trying to eat all of the blockchain is github.com/faddat/ingestron

I don't think that it's a bug in go-steem/rpc, it's just that (I think) you hit the same difficulties that I did.  Either that or I am using go-steem/rpc incorrectly.  You did make an excellent tool here.  Also, at github.com/faddat/steemconnect you can find a library that you may want to include in go-steem:  It makes connecting to a blockchain API into a single function in apps that import it instead of ~100 LOC.  It's mostly a "cleanliness" thing so that its users don't need to scroll through a whole bunch of connect-y code.  

But most of all great job on the hack to the connection code :).  I'd be going entirely in circles if you hadn't figured that out.

**Comment by tchap** [comment]
@faddat You still haven't said anything about the issues you are having :-) What difficulties are you hitting? What error messages are you getting? I will take a look at the code you mentioned, though...

**Comment by faddat** [comment]
I don't think that this is a bug in your code.  I am sorry I thought I'd
described it well but I think I haven't.  No errors especially as pertains
to your code.

Pseudo code:

U = 0; For U <= props.lastirreversibleblocknum {
Block := uint32(U)
gotblock := GetBlock(block)

}

I imagine that loop is somewhat familiar.  So now what I want to do is
access each and every field in the return.  GetBlock doesn't (at least I do
not think it does) let me access and/or manipulate items under the
operations key.  Now in the code I linked to I'm using GetBlockRaw and
unmarshaling onto a struct.  I built my struct with json-to-go..... BUT
there are many variants of what data looks like under the operations key.
Due to that I haven't been able to put together a struct that effectively
fits each block.

I am a bit of a noob.  It is totally possible that I am missing something
that should be obvious.

Hope I did a better job explaining this time, and when I am no longer in
transit from Hanoi to Siam Reap, I will clean up that example code.  I
think the reason it looks how it does is that I copied it from my repo to
the pull request on GitHub.  Will resubmit.  Thanks!

**Comment by tchap** [comment]
@faddat Actually when you use `GetBlock`, you can access the operations array, and `go-steem/rpc` is clever enough to unmarshal the operations, even though the format is weird. You can access the operations in `Block.Transactions.Operations`, e.g.

``` go
for _, tx := range block.Transactions {
    for _, op := range tx.Operations {
        processOperation(op)
    }
}
```

Now, `op` is an interface: https://godoc.org/github.com/go-steem/rpc/types#Operation . To get the underlying operation object, the data you want, you have to call `Data()` on `op`. This returns an `interface{}`, though, so you need to use a type switch to get the real object, e.g.

``` go
func processOperation(op types.Operation) {
    switch op := op.Data().(type) {
    case *types.VoteOperations:
        // Process vote_operation.
    case *types.CommentOperations:
        // Process comment_operation.
    case ... // Add as many cases for particular operation types you need to process.
    }
}
```

You can actually find a working example here: https://github.com/go-steem/rpc/blob/master/examples/voting_monitor/main.go#L121

**Comment by tchap** [comment]
@faddat Actually for you particular use case you can just take that example at https://github.com/go-steem/rpc/blob/master/examples/voting_monitor/main.go#L121 as a skeleton and just insert your custom code where necessary...

**Comment by faddat** [comment]
Actually, this explains a LOT.  I couldn't figure out why there were JSON references  to the operation types.  Well, I guess this is what happens when you learn a new language, sometimes things go sideways because you totally miss something altogether.  

Anyway, many thanks @tchap!  I think I get this now :D.  

Also, BTW:  voting_monitor was totally my reference point for ingestron :).  It made a splendid framework for the app.

**Comment by tchap** [comment]
@faddat Yeah, perhaps the documentation is not too clear, but that is why there is the example :-) Unfortunately it cannot be much clearer because of how Steem blockchain serializes things in relatively stupid way considering statically typed languages. But cool it is clear now. Have fun with Go ;-)

**Comment by faddat** [comment]
Certainly having fun.... and.....

Yes, steem does things in the most obscenely bizarre fashion possible.  I'll be moving on from it shortly....
